package:
  name: csdms-components
  version: "0.1"

requirements:
  build:
    - cmake
    - python
    - setuptools
    - cca-babel
    - cca-spec-babel
    - ccaffeine
    - cca-bocca
    - bmi-babel
    - pexpect
    - glib
    - pkgconfig

  run:
    - cmake
    - python
    - setuptools
    - cca-babel
    - cca-spec-babel
    - ccaffeine
    - cca-bocca
    - bmi-babel
    - pexpect
    - glib

about:
  summary: Babelized components ready to be used in the CSDMS framework.
