package:
  name: cem
  version: "0.1"

source:
  git_url: https://github.com/csdms/cem-old
  git_rev: mcflugen/add-function-pointers

build:
  number: 2

requirements:
  build:
    - cmake
    - pkgconfig-command [osx]
    - glib [osx]

  run:
    - glib [osx]
