package:
  name: csdms-stack
  version: "0.1"

requirements:
  build:
    - csdms-components
    - coupling
    - wmt-exe

  run:
    - csdms-components
    - coupling
    - wmt-exe

about:
  summary: The complete CSDMS software stack.
