package:
  name: rafem
  version: "0.1"

source:
  git_url: https://github.com/mcflugen/avulsion-bmi
  git_rev: add-bmi-metadata

build:
  number: 3

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
