package:
  name: rafem
  version: "0.1"

source:
  git_url: https://github.com/mcflugen/avulsion-bmi
  git_rev: add-bmi-metadata

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy

build:
  number: 3
  string: {{ environ.get('BUILD_STR', '') }}
