package:
  name: boccatools
  version: "0.1"

source:
  git_url: https://github.com/csdms/bocca-tools
  git_rev: master

requirements:
  build:
    - cca-bocca

  run:
    - cca-bocca

about:
  summary: Python utilities for working with bocca projects.
