os:
- linux
- osx
env:
  global:
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: vFg2xua6eU76izFp6Mh9TU73EfC2INk/+agxZws6mbgo8gO91yPDJcpNA8/nl2T4u6E17qXFMIL0DerOx4uqtc6JIylICZJfF/CnTnn7s+y9lt6iQRz3FqfKoyEtLvJOGTr6z3TAGru63ef4836FPc1Bm0Xts2S5NVGhNJXYNMWh8V9Zu2NgdsUkppgvx/DV+7x5jJErmaH3DKxFaXxaYAb5vQzP0wkK68xlPBDeDnvisxrJ74IjRBH94A0SiNAkbnTnly+ClYRrXPA5ifx55wVqD6t9xcjyw9xwBakqYOvpDLMLikOM+VBnGNGQpImLwQw/lY4VQ3tZ19VLMzjUy2Ygdit8msulhAJdBA0Q7o6+7/JAkomm8cW/4EjlEe24o5UXI8+H0rphtdZsJAAGwGpt+z1ohsidxTVPrC6FRoO0iw6yJCk5Tr0WJqEO3p1sllkBdRh9Foj8FATTm9XAGUtqd0fouHARxFeJ5IREXihyOp3hlKMI4KZ/SpjvP7GSn/Fi4DSyjy01TZ5gCbLAFtK7a9W+NICR6WK6ErjkoG+mm05z2gIHyIYUaCIZba/lGOKq0GEXTMguBdM8jfQF0zy2igR6pKBl1YHZVAsQTLR27UrNiymCmikoL0O4NcJFMRqiNorXYeiClGGmoEemPJMel9mgnrYivJfiDte27ms=
  - secure: QYSoKqc5l+gmoPmk+gWhvoQLU2UVyRBx5VyyrPUGfbyLXRZ/TZQpdiRakcckr4hWGf8O2iZfgyWnc4axlukIVhlpBX6LdRmiSQG0HZWMElc9vRlQX4AVnYiF/B47WIPcWJs8Q/nnrAXNmyGZ6mT8lVDtENgr8OsNiRcMS7yCRJ90oViVSq9zCkEssfb1+1jDlF+mdOe6Bscwp5MoJbKiopcwV8avUIT8X5yC2xj8Kqa/6+v3sZDuJ30QWBgU5x3Ul1cIPbnJDFWzw4arS8DlgUV71oVTIPXOeMvue9E8LTz5u9+4RBwWEgQnR9QVAP7u3Ct5SXWLpPon7IYFluR0PcwpjXPpnSg9cGhN+dsbyel9B3GqyCFDRv7GC+J+swod2C6smNiEi38HdjnutAdsXwzQWUEM15FZPS6np8W+ofYZGqXbQ099XYMEBC2Cm0XBANt0ZeoFLbmTUc12y98dmJYYe0xKvMCGuF4HHhzjMxVqMWEwGMJgq0c47iynS8LMpM86Cujtt9uCu8nXelZ4K7uZEnn2sQsIjBKVAnwrVK06WpEy6ce8acidhVBplNPT2zQsitn5mWvrIHCbDxIfxQbfwTLTm0LZ9Pv3hWs8T/3VTfPGa3wG5Bhrt34rLMAt/cjrmH0qH//gWozSGqe/yOhA9VMQy2oUKO/gtjrfF+c=
  matrix:
  - CONDA_RECIPES="runtime"
  - CONDA_RECIPES="conda-recipes/libffi conda-recipes/gettext conda-recipes/glib"
sudo: false
install:
- bash .ci/travis/install_python.sh
- export PATH=$HOME/miniconda/bin:$PATH
- conda install conda-build anaconda-client
script:
- if [ $CONDA_RECIPES == "runtime" ]; then
    conda install csdms-models coupling -c csdms/channel/nightly;
    python -c 'from cmt.components import Hydrotrend; Hydrotrend()';
  fi
- if [ $CONDA_RECIPES != "runtime" ]; then
    bash ./.ci/travis/build_recipes.sh $CONDA_RECIPES;
    export CONDA_FILES_TO_UPLOAD=$(conda build --output --python=$TRAVIS_PYTHON_VERSION --numpy=$NUMPY_VERSION $CONDA_RECIPES);
  fi
deploy:
  provider: script
  skip_cleanup: true
  script: .ci/travis/deploy_to_anaconda.sh
  on:
    branch: master
