os:
- linux
- osx
env:
  global:
  - BUILD_STR="dev"
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: e8CGoHePbGgSRYsooZIC4C8g155e/W7mOoxk6a0M3D6xoHhuszU55EGvl3+fgJSYGdivHguXEDxaX0xm80T3Gwv0dJ4wRQxmkFIkob2tvVF5NbcPYbNhofnpt4yUkjihiG+Y4OGXE1xbtFtuLPcckcL5n1isr8S81n67WbKknDDNSaWB8684guGOFQBNcP4zbAWEHx8Bqfl73wr6e4loPNZ5H+DLhYni0qYqKw6luNQbYf4Dtmi+wDAYe2TRX0FkwHfPBCF+eZlkrZbZ2dhjFpChepRI9Op52GD3i9Xel4ZjOjqACywoCBaqSnuud/u2W4S9QQxVfUJPCBaT8Zi5gm8wn1LXOZJy99na5csr65nX22VX4XSTSpDaJmFH0nudxVjgk4Dj15P5QpgE+jui98/hvL2VzOk8rcwRpXBMT8aCqH0LhT1RstkAIQgB7lj0Z0mIhQeNUc4OaNCozlSLRKizDfcEeiSj0GwWsfet0tdzBb5XSyl9UwuPQhhTdV7ZDln+ittdM4ulseFOFzfc4N7sIbDr4lp7aqBsEG1mJ/sc8M1UWBKoHeyZ8n19Z3/OuZ0pYA3EVz1PPb0feZxXCSwcTrzOCGTwyoCxR9/V/YUnQnN/ewK+AAXWmnizFQp6WpFTct2hHbpIs7lCGETMDh9NkzQqz5IEVy/4jP0NK4E=
  - secure: vFg2xua6eU76izFp6Mh9TU73EfC2INk/+agxZws6mbgo8gO91yPDJcpNA8/nl2T4u6E17qXFMIL0DerOx4uqtc6JIylICZJfF/CnTnn7s+y9lt6iQRz3FqfKoyEtLvJOGTr6z3TAGru63ef4836FPc1Bm0Xts2S5NVGhNJXYNMWh8V9Zu2NgdsUkppgvx/DV+7x5jJErmaH3DKxFaXxaYAb5vQzP0wkK68xlPBDeDnvisxrJ74IjRBH94A0SiNAkbnTnly+ClYRrXPA5ifx55wVqD6t9xcjyw9xwBakqYOvpDLMLikOM+VBnGNGQpImLwQw/lY4VQ3tZ19VLMzjUy2Ygdit8msulhAJdBA0Q7o6+7/JAkomm8cW/4EjlEe24o5UXI8+H0rphtdZsJAAGwGpt+z1ohsidxTVPrC6FRoO0iw6yJCk5Tr0WJqEO3p1sllkBdRh9Foj8FATTm9XAGUtqd0fouHARxFeJ5IREXihyOp3hlKMI4KZ/SpjvP7GSn/Fi4DSyjy01TZ5gCbLAFtK7a9W+NICR6WK6ErjkoG+mm05z2gIHyIYUaCIZba/lGOKq0GEXTMguBdM8jfQF0zy2igR6pKBl1YHZVAsQTLR27UrNiymCmikoL0O4NcJFMRqiNorXYeiClGGmoEemPJMel9mgnrYivJfiDte27ms=
  - secure: QYSoKqc5l+gmoPmk+gWhvoQLU2UVyRBx5VyyrPUGfbyLXRZ/TZQpdiRakcckr4hWGf8O2iZfgyWnc4axlukIVhlpBX6LdRmiSQG0HZWMElc9vRlQX4AVnYiF/B47WIPcWJs8Q/nnrAXNmyGZ6mT8lVDtENgr8OsNiRcMS7yCRJ90oViVSq9zCkEssfb1+1jDlF+mdOe6Bscwp5MoJbKiopcwV8avUIT8X5yC2xj8Kqa/6+v3sZDuJ30QWBgU5x3Ul1cIPbnJDFWzw4arS8DlgUV71oVTIPXOeMvue9E8LTz5u9+4RBwWEgQnR9QVAP7u3Ct5SXWLpPon7IYFluR0PcwpjXPpnSg9cGhN+dsbyel9B3GqyCFDRv7GC+J+swod2C6smNiEi38HdjnutAdsXwzQWUEM15FZPS6np8W+ofYZGqXbQ099XYMEBC2Cm0XBANt0ZeoFLbmTUc12y98dmJYYe0xKvMCGuF4HHhzjMxVqMWEwGMJgq0c47iynS8LMpM86Cujtt9uCu8nXelZ4K7uZEnn2sQsIjBKVAnwrVK06WpEy6ce8acidhVBplNPT2zQsitn5mWvrIHCbDxIfxQbfwTLTm0LZ9Pv3hWs8T/3VTfPGa3wG5Bhrt34rLMAt/cjrmH0qH//gWozSGqe/yOhA9VMQy2oUKO/gtjrfF+c=
  matrix:
#  - CONDA_RECIPES="runtime"
#  - CONDA_RECIPES="development"
#  - CONDA_RECIPES="cca-babel cca-spec-babel ccaffeine cca-bocca"
  - CONDA_RECIPES="chasm"
  - CONDA_RECIPES="boost-headers"
#  - CONDA_RECIPES="libffi gettext glib"
#  - CONDA_RECIPES="libxml2"
#  - CONDA_RECIPES="boost-headers"
#  - CONDA_RECIPES="sedflux"
#  - CONDA_RECIPES="topoflow"
#  - CONDA_RECIPES="cem"
#  - CONDA_RECIPES="hydrotrend"
sudo: false
install:
- bash .ci/travis/install_python.sh
- export PATH=$HOME/miniconda/bin:$PATH
- conda install conda-build anaconda-client
script:
# - bash .ci/travis/test_stack.sh
 - cd conda-recipes
 - CONDA_FILES_TO_UPLOAD=$(conda build --output --python=$TRAVIS_PYTHON_VERSION --numpy=$NUMPY_VERSION $CONDA_RECIPES)
 - echo $CONDA_FILES_TO_UPLOAD
 - conda build $CONDA_RECIPES -c csdms && anaconda -t $ANACONDA_TOKEN upload --force --user csdms --channel $BUILD_STR $CONDA_FILES_TO_UPLOAD
# - conda build cca-babel -c csdms
# - conda build cca-spec-babel -c csdms
# - conda build ccaffeine -c csdms
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: .ci/travis/deploy_to_anaconda.sh
#  on:
#    branch: master
