os:
  - linux
  - osx

env:
  global:
    - TRAVIS_PYTHON_VERSION="2.7"

sudo: false

install:
  - bash .ci/travis/install_python.sh
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda install conda-build

script:
  - conda install csdms-components coupling -c csdms/channel/nightly
  - python -c 'from cmt.components import Hydrotrend; Hydrotrend()'
