language: java

jdk:
  - openjdk7

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -f -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - echo $(which gcc)
  - echo $(which gfortran)
  - echo $(gcc --version)
  - echo $(gfortran --version)

script:
  - cd conda-recipes
  - conda build libffi > build.log || (tail -500 build.log && exit 1)
  - conda build glib > build.log || (tail -500 build.log && exit 1)
  - conda build netcdff > build.log || (tail -500 build.log && exit 1)
  - conda build libxml2 > build.log || (tail -500 build.log && exit 1)
  - conda build boost-headers > build.log || (tail -500 build.log && exit 1)
  - conda build chasm > build.log || (tail -500 build.log && exit 1)
  - conda build cca-babel > build.log || (tail -500 build.log && exit 1)
  - conda build cca-spec-babel > build.log || (tail -500 build.log && exit 1)
  - conda build ccaffeine > build.log || (tail -500 build.log && exit 1)
  - conda build cca-bocca > build.log || (tail -500 build.log && exit 1)
  - conda build bmi-babel > build.log || (tail -500 build.log && exit 1)
  - conda build csdms-components > build.log || (tail -500 build.log && exit 1)
  - conda build esmf > build.log || (tail -500 build.log && exit 1)
  - conda build esmpy > build.log || (tail -500 build.log && exit 1)
  - conda build coupling > build.log || (tail -500 build.log && exit 1)
  - conda build wmt-exe > build.log || (tail -500 build.log && exit 1)
