language: java

jdk:
  - openjdk7

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -f -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda install gcc
  - conda install conda-build

script:
  - cd conda-recipes
  - bash ./build-stack.sh
