package:
  name: csdms-cem
  version: "0.1"

build:
  number: 3
  rpaths:
    - lib/
    - lib/cca-spec-babel-0_8_6-babel-1.4.0

requirements:
  build:
    - cem
    - bmi-babel
  run:
    - cem
    - bmi-babel
