package:
  name: csdms-sedflux
  version: "2.1"

build:
  rpaths:
    - lib/
    - lib/cca-spec-babel-0_8_6-babel-1.4.0

requirements:
  build:
    - sedflux
    - bmi-babel
  run:
    - sedflux
    - bmi-babel
