package:
  name: cca-spec-babel
  version: "0.8.6"

source:
  git_url: https://github.com/csdms/cca-spec-babel

requirements:
  build:
    - python
    - cca-babel
    - libxml2
    - libiconv [osx]

  run:
    - python
    - cca-babel
    - libxml2
    - libiconv [osx]

build:
  string: {{ environ.get('BUILD_STR', '') }}
