package:
  name: wmt-exe
  version: "0.1"

source:
  git_url: https://github.com/csdms/wmt-exe
  git_rev: master

requirements:
  build:
    - python
    - csdms-models
    - coupling

  run:
    - python
    - csdms-models
    - coupling

about:
  summary: The Web Modeling Tool execution server.
