package:
  name: cca-bocca
  version: "0.5.7"

source:
  git_url: https://github.com/csdms/cca-bocca
  patches:
    - configure-input.patch
    - fix-config-sub.patch

requirements:
  build:
    - python
    - cca-babel
    - cca-spec-babel
    - ccaffeine
  run:
    - python
    - cca-babel
    - cca-spec-babel
    - ccaffeine

build:
  string: {{ environ.get('BUILD_STR', '') }}
