package:
  name: esmpy
  version: "6.3.0"

source:
  fn: esmf_6_3_0rp1_src.tar.gz
  url: https://sourceforge.net/projects/esmf/files/ESMF_6_3_0r/ESMF_6_3_0rp1/esmf_6_3_0rp1_src.tar.gz/download

requirements:
  build:
    - python
    - esmf
    - libnetcdf
    - netcdff
    - numpy

  run:
    - python
    - esmf
    - libnetcdf
    - netcdff
    - numpy

build:
  string: {{ environ.get('BUILD_STR', '') }}
