package:
  name: libparsifal
  version: "1.0.0"

source:
  git_url: https://github.com/csdms/cca-babel

requirements:
  build:
    - gcc

  run:
    - libgcc
    - libgfortran

build:
  script_env:
    - JAVA_HOME
  string: {{ environ.get('BUILD_STR', '') + environ.get('COMPILER', '') }}
