package:
  name: sedflux
  version: "2.1"

source:
  git_url: https://github.com/mcflugen/sedflux
  git_rev: add-function-pointers

requirements:
  build:
    - cmake
    - glib [osx]
  run:
    - glib [osx]

build:
  string: {{ environ.get('BUILD_STR', '') }}
