package:
  name: csdms-topoflow
  version: "3.4"

build:
  number: 1
  rpaths:
    - lib/
    - lib/cca-spec-babel-0_8_6-babel-1.4.0

requirements:
  build:
    - topoflow
    - bmi-babel
  run:
    - topoflow
    - bmi-babel
