package:
  name: cca-babel
  version: "1.4.0"

source:
  git_url: https://github.com/csdms/cca-babel
  patches:
    - mac-inline.patch [osx]
    - override-java.patch [linux]

build:
  script_env:
    - JAVA_HOME

requirements:
  build:
    - python
    - numpy
    - libxml2
    - chasm
    - pkgconfig-command [osx]

  run:
    - python
    - numpy
    - libxml2
    - chasm
    - pkgconfig-command [osx]
