package:
  name: cca-babel
  version: "1.4.0"

source:
  fn: babel-1.4.0.tar.gz
  url: http://computation.llnl.gov/casc/components/docs/babel-1.4.0.tar.gz
  patches: [osx]
    - mac-inline.patch [osx]

build:
  script_env:
    - JAVA_HOME

requirements:
  build:
    - gcc
    - python
    - numpy
    - libxml2
    - chasm

  run:
    - gcc
    - python
    - numpy
    - libxml2
    - chasm
