package:
  name: cca-babel
  version: "1.4.0"

source:
  git_url: https://github.com/csdms/cca-babel
  patches:
    - mac-inline.patch [osx]
    - override-java.patch [unix]

requirements:
  build:
    - python
    - numpy
    - libxml2
    - gcc
    - libgcc
    - libgfortran
    - chasm
    - libparsifal
    - libtool
    - pkgconfig

  run:
    - python
    - numpy
    - libxml2
    - gcc
    - libgcc
    - libgfortran
    - chasm
    - libparsifal
    - libtool
    - pkgconfig

build:
  script_env:
    - JAVA_HOME
    - CC
    - CXX
    - FC
  string: {{ environ.get('BUILD_STR', '') + environ.get('COMPILER', '') }}
