package:
  name: ccaffeine
  version: "0.8.8"

source:
  git_url: https://github.com/csdms/ccaffeine
  patches:
    - cxxflags-linux.patch [linux]
    - cxxflags-osx.patch [osx]

requirements:
  build:
    - python
    - libxml2
    - cca-spec-babel
    - cca-babel
    - boost-headers
    - readline
    - ncurses

  run:
    - python
    - libxml2
    - cca-spec-babel
    - cca-babel
    - boost-headers
    - readline
    - ncurses
