package:
  name: landlab
  version: "0.1.33"

source:
  git_url: https://github.com/landlab/landlab

requirements:
  build:
    - python
    - scipy
    - numpy
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - setuptools

  run:
    - python
    - scipy
    - numpy
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - setuptools

build:
  string: {{ environ.get('BUILD_STR', '') }}
