package:
  name: csdms-rafem
  version: "0.1"

build:
  rpaths:
    - lib/
    - lib/cca-spec-babel-0_8_6-babel-1.4.0

requirements:
  build:
    - rafem
    - bmi-babel
  run:
    - rafem
    - bmi-babel
