package:
  name: chasm
  version: "1.4"

source:
  fn: chasm_1.4.RC3.tar.gz
  url: http://sourceforge.net/projects/chasm-interop/files/chasm_1.4.RC3.tar.gz

requirements:
  build:
    - gcc [linux]
    - libgcc [linux]
#   run:
#     - gcc
#     - libgcc

build:
  string: {{ environ.get('BUILD_STR', '') + environ.get('COMPILER', '') }}
